
name: Deploy Website


on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploying to surge
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14.4
      #install yarn
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run 'yarn install' command and try again
        
      - name: Build React App
        run: yarn build
      - name: Install Surge
        run: npm install -g surge
      - name: Run surge
        run: surge ./build etracker_am.surge.sh --token ${{secrets.SURGE_TOKEN_REACT}}
